/**
 * Firestore Collection Schemas - Phase 5
 * Complete schema documentation for all Phase 5 collections
 *
 * Collections follow pattern:
 * - Subcollections for hierarchical data
 * - Denormalized metadata for faster queries
 * - Timestamps in milliseconds (firestore.Timestamp.now().toMillis())
 * - IDs generated by Firestore auto-increment
 */

// Type documentation only - no runtime imports needed

// ============================================================
// REPORT CARDS COLLECTION
// ============================================================
// Path: monthly_report_cards/{reportId}
// Index: userId, year, month (composite)
export interface MonthlyReportCardDoc {
  userId: string;
  year: number;
  month: number; // 1-12
  ecoScore: number;
  ecoScoreChange: number;
  carbonSaved: number;
  carbonSavedChange: number;
  currentStreak: number;
  bestStreak: number;
  bestHabit: string | null;
  bestCategory: "food" | "transport" | "energy" | null;
  communityRanking: number | null;
  achievements: {
    id: string;
    title: string;
    description: string;
    unlockedAt: number;
  }[];
  generatedAt: number;
  viewedAt?: number;
  sharedAt?: number;
  shareCount: number;
  thumbnail?: string; // Base64 preview
}

// Subcollection: monthly_report_cards/{reportId}/views
export interface ReportViewDoc {
  userId: string;
  viewedAt: number;
  referrer?: string;
  platform?: "web" | "mobile" | "social";
}

// ============================================================
// BADGES COLLECTION
// ============================================================
// Path: badges/{badgeId}
// Index: category, rarity
export interface BadgeDefinitionDoc {
  id: string;
  name: string;
  description: string;
  category: "streak" | "habit" | "social" | "milestone";
  icon: string;
  color: string;
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
  unlockCondition: {
    type: "streak" | "count" | "challenge" | "time_based" | "custom";
    target?: number;
    category?: string;
    duration?: number;
    condition?: string;
  };
  createdAt: number;
}

// Path: user_badges/{userBadgeId}
// Index: userId, badgeId, unlockedAt
export interface UserBadgeDoc {
  userId: string;
  badgeId: string;
  unlockedAt: number;
  progress: number;
  isNew: boolean;
  notificationSent: boolean;
}

// ============================================================
// FRIEND CIRCLES COLLECTION
// ============================================================
// Path: circles/{circleId}
// Index: ownerId, createdAt, visibility
export interface CircleDoc {
  name: string;
  description: string;
  ownerId: string;
  visibility: "private" | "friends_only" | "public";
  createdAt: number;
  updatedAt: number;
  stats: {
    totalMembers: number;
    totalEcoScore: number;
    averageEcoScore: number;
    weeklyProgress: number;
    activeMembers: number;
  };
}

// Subcollection: circles/{circleId}/members
export interface CircleMemberDoc {
  userId: string;
  role: "owner" | "admin" | "member";
  joinedAt: number;
  lastActivity: number;
  contribution: number;
  status: "active" | "inactive";
}

// Subcollection: circles/{circleId}/invites
export interface CircleInviteDoc {
  circleId: string;
  invitedBy: string;
  invitedEmail: string;
  invitedAt: number;
  expiresAt: number;
  status: "pending" | "accepted" | "declined" | "expired";
}

// Subcollection: circles/{circleId}/rankings
export interface CircleWeeklyRankingDoc {
  week: number;
  year: number;
  rankings: {
    rank: number;
    userId: string;
    ecoScore: number;
    activities: number;
    change: number;
  }[];
  generatedAt: number;
}

// ============================================================
// COMMUNITY CHALLENGES COLLECTION
// ============================================================
// Path: community_challenges/{challengeId}
// Index: status, type, startDate, endDate
export interface CommunityChallengeDoc {
  title: string;
  description: string;
  type: "food" | "transport" | "energy" | "general";
  difficulty: "easy" | "medium" | "hard";
  status: "draft" | "active" | "ended" | "archived";
  goal: string;
  icon: string;
  color: string;
  startDate: number;
  endDate: number;
  participants: number;
  createdAt: number;
  createdBy: string;
}

// Subcollection: community_challenges/{challengeId}/participants
export interface ChallengeParticipantDoc {
  challengeId: string;
  userId: string;
  joinedAt: number;
  progress: number; // 0-100
  completedAt?: number;
  rank?: number;
}

// Subcollection: community_challenges/{challengeId}/entries
export interface ChallengeEntryDoc {
  challengeId: string;
  userId: string;
  activityId: string;
  loggedAt: number;
  value: number;
}

// Subcollection: community_challenges/{challengeId}/leaderboard
export interface ChallengeLeaderboardDoc {
  rank: number;
  userId: string;
  userName: string;
  progress: number;
  entries: number;
  generatedAt: number;
}

// ============================================================
// LEADERBOARDS COLLECTION
// ============================================================
// Path: leaderboards/{leaderboardId}
// Index: scope, metric, period, generatedAt
export interface LeaderboardDoc {
  scope: "global" | "city" | "country" | "friends" | "circle";
  location?: {
    city?: string;
    country?: string;
    region?: string;
  };
  metric: "eco_score" | "streak" | "challenges" | "carbon_saved";
  period: "weekly" | "monthly" | "alltime";
  generatedAt: number;
  expiresAt: number;
  rankings: {
    rank: number;
    userId: string;
    userName: string;
    avatarUrl?: string;
    metric: number;
    change: number;
    trend: "up" | "down" | "neutral";
    badges: string[];
    lastActivityAt: number;
  }[];
}

// Path: user_leaderboard_positions/{userId}
// Index: userId
export interface UserLeaderboardPositionDoc {
  userId: string;
  positions: {
    global?: {
      eco_score?: { rank: number; value: number; percentile: number };
      streak?: { rank: number; value: number; percentile: number };
      challenges?: { rank: number; value: number; percentile: number };
      carbon_saved?: { rank: number; value: number; percentile: number };
    };
    city?: {
      eco_score?: { rank: number; value: number; percentile: number };
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
  updatedAt: number;
}

// ============================================================
// REFERRAL SYSTEM COLLECTION
// ============================================================
// Path: referral_codes/{codeId}
// Index: userId, code, isActive
export interface ReferralCodeDoc {
  userId: string;
  code: string; // Unique
  createdAt: number;
  expiresAt?: number;
  isActive: boolean;
  stats: {
    invitesSent: number;
    signupsGenerated: number;
    ecoPointsEarned: number;
    bestMonthEarnings: number;
  };
}

// Subcollection: referral_codes/{codeId}/invites
export interface ReferralInviteDoc {
  referralCodeId: string;
  referrerId: string;
  invitedEmail: string;
  invitedAt: number;
  status: "pending" | "signed_up" | "declined" | "expired";
  signedUpAt?: number;
  newUserId?: string;
}

// Path: referral_rewards/{rewardId}
// Index: referrerId, status, awardedAt
export interface ReferralRewardDoc {
  referrerId: string;
  referralId: string;
  ecoPointsAwarded: number;
  reason: "invite_accepted" | "first_week_active" | "first_month_active";
  awardedAt: number;
  claimed: boolean;
  claimedAt?: number;
}

// Path: user_referral_profiles/{userId}
export interface UserReferralProfileDoc {
  userId: string;
  referralCodeId?: string;
  totalEarnings: number;
  pendingRewards: number;
  claimedRewards: number;
  referredBy?: string;
  referredByCode?: string;
  joinedViaReferral: boolean;
  updatedAt: number;
}

// ============================================================
// NOTIFICATIONS COLLECTION
// ============================================================
// Path: notifications/{notificationId}
// Index: userId, createdAt, readAt
export interface NotificationDoc {
  userId: string;
  type: string;
  title: string;
  body: string;
  data: Record<string, string>;
  priority: "high" | "normal" | "low";
  createdAt: number;
  sentAt?: number;
  readAt?: number;
  actionUrl?: string;
}

// Path: notification_preferences/{userId}
export interface NotificationPreferencesDoc {
  userId: string;
  channels: {
    fcm: boolean;
    inApp: boolean;
    email: boolean;
  };
  types: Record<string, boolean>;
  quietHours: {
    enabled: boolean;
    startTime: number;
    endTime: number;
  };
  updatedAt: number;
}

// Path: fcm_tokens/{tokenId}
export interface FCMTokenDoc {
  userId: string;
  token: string;
  platform: "web" | "ios" | "android";
  registeredAt: number;
  lastUsedAt: number;
  isActive: boolean;
}

// ============================================================
// SHAREABLE CARDS COLLECTION
// ============================================================
// Path: shareable_cards/{cardId}
// Index: userId, type, createdAt
export interface ShareableCardDoc {
  userId: string;
  type: "eco_score" | "streak" | "monthly_report" | "achievement" | "challenge";
  data: Record<string, unknown>;
  createdAt: number;
  expiresAt?: number;
  stats: {
    generated: number;
    shared: number;
    clicked: number;
    platforms: Record<string, number>;
  };
}

// Subcollection: shareable_cards/{cardId}/shares
export interface ShareEventDoc {
  cardId: string;
  userId: string;
  platform: "twitter" | "facebook" | "whatsapp" | "instagram" | "email" | "link";
  sharedAt: number;
  clickedAt?: number;
  campaignId?: string;
}

// ============================================================
// ANALYTICS COLLECTION (BigQuery Integration)
// ============================================================
// Path: analytics_events/{eventId}
// Automatically synced to BigQuery via Firestore export
export interface AnalyticsEventDoc {
  userId: string;
  eventName: string; // see Analytics Constants below
  timestamp: number;
  properties: Record<string, unknown>;
  sessionId: string;
  platform: "web" | "mobile";
}

// Analytics Event Names (for BigQuery queries)
export const ANALYTICS_EVENTS = {
  REPORT_GENERATED: "report_generated",
  REPORT_VIEWED: "report_viewed",
  REPORT_SHARED: "report_shared",
  BADGE_UNLOCKED: "badge_unlocked",
  BADGE_SHARED: "badge_shared",
  CHALLENGE_JOINED: "challenge_joined",
  CHALLENGE_COMPLETED: "challenge_completed",
  LEADERBOARD_VIEWED: "leaderboard_viewed",
  FRIEND_INVITED: "friend_invited",
  CIRCLE_CREATED: "circle_created",
  CIRCLE_JOINED: "circle_joined",
  CARD_GENERATED: "card_generated",
  CARD_SHARED: "card_shared",
  CARD_CLICKED: "card_clicked",
} as const;
